name = "Compressor"
revision = 1
website = "https://socalabs.com/effects/compressor/"
vendor = "SocaLabs"
categories = ["COMPRESSOR"]
description = """
    Mono or Stereo Compressor
    Soft knee
    Cool visualization
    Windows VST/VST3 32/64
    Mac VST/VST3/AU 64
"""

[[instance]]
format = "VST2"
platform = "WINDOWS"
arch = "X86_64"

[[instance.method.SimpleDownloadAndCopy.downloads]]
url = "https://socalabs.com/files/get.php?id=Compressor_Win.zip"
extract = "Zip"
copy_actions = [
    ["%dl%/vst/Compressor.dll", "%plugs%/socalabs/Compressor.dll"],
]

[[instance]]
format = "VST3"
platform = "WINDOWS"
arch = "X86_64"

[[instance.method.SimpleDownloadAndCopy.downloads]]
url = "https://socalabs.com/files/get.php?id=Compressor_Win.zip"
extract = "Zip"
copy_actions = [
    ["%dl%/vst3/Compressor.vst3", "%plugs%/socalabs/Compressor.vst3"],
]
